from cmath import acosh
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.DynamicConfiguration import StringList
from codeallybasic.UnitTestBase import UnitTestBase

from umlshapes.lib.ogl import FORMAT_CENTRE_HORIZ
from umlshapes.lib.ogl import FORMAT_CENTRE_VERT
from umlshapes.lib.ogl import FORMAT_NONE
from umlshapes.lib.ogl import FORMAT_SIZE_TO_CONTENTS

from umlshapes.links.UmlAssociationLabelFormat import UmlAssociationLabelFormat
from umlshapes.preferences.UmlPreferences import DEFAULT_ASSOCIATION_LABEL_FORMAT



class TestUmlAssociationLabelFormat(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 25 August 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testDefaultsToWxFormat(self):

        expectedValue: int = FORMAT_CENTRE_VERT | FORMAT_CENTRE_HORIZ
        actualValue: int = UmlAssociationLabelFormat.toWxFormat(DEFAULT_ASSOCIATION_LABEL_FORMAT)

        self.assertEqual(expectedValue, actualValue, 'Failure !!')

    def testAllOptionsToWxFormat(self):
        allValues: str = (
            f'{UmlAssociationLabelFormat.FORMAT_NONE.value},'
            f'{UmlAssociationLabelFormat.FORMAT_CENTER_VERTICAL.value},'
            f'{UmlAssociationLabelFormat.FORMAT_CENTER_HORIZONTAL.value},'
            f'{UmlAssociationLabelFormat.FORMAT_SIZE_TO_CONTENTS.value}'
        )

        expectedValue: int = FORMAT_NONE | FORMAT_CENTRE_VERT | FORMAT_CENTRE_HORIZ | FORMAT_SIZE_TO_CONTENTS

        actualValue: int = UmlAssociationLabelFormat.toWxFormat(allValues)

        self.assertEqual(expectedValue, actualValue, 'Failure !!')

    def testDefaultsToDelimitedString(self):
        defaultMode: int = FORMAT_CENTRE_VERT | FORMAT_CENTRE_HORIZ
        actualStr:   str = UmlAssociationLabelFormat.toDelimitedString(defaultMode)

        self.assertEqual(DEFAULT_ASSOCIATION_LABEL_FORMAT, actualStr, 'Bit wise ops did not work')

    def testSetMode(self):
        currentMode:  int = 0
        expectedMode: int = FORMAT_CENTRE_VERT
        actualMode:   int = UmlAssociationLabelFormat.setMode(wxMode=FORMAT_CENTRE_VERT, wxValue=currentMode)

        self.assertEqual(expectedMode, actualMode, 'Mode setting did not work')

    def testClearMode(self):
        currentMode:  int = FORMAT_CENTRE_VERT | FORMAT_CENTRE_HORIZ
        expectedMode: int = FORMAT_CENTRE_HORIZ

        actualMode: int = UmlAssociationLabelFormat.clearMode(wxMode=FORMAT_CENTRE_VERT, wxValue=currentMode)

        self.assertEqual(expectedMode, actualMode, 'Mode clearing is broken.')

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUmlAssociationLabelFormat))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
