
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallyadvanced.ui.UnitTestBaseW import UnitTestBaseW

from umlmodel.Actor import Actor
from umlmodel.Class import Class
from umlmodel.Link import Link
from umlmodel.Note import Note

from umlshapes.lib.ogl import OGLInitialize
from umlshapes.links.UmlLink import UmlLink
from umlshapes.mixins.IdentifierMixin import InvalidOperationError

from umlshapes.shapes.UmlActor import UmlActor
from umlshapes.shapes.UmlClass import UmlClass
from umlshapes.shapes.UmlNote import UmlNote
from umlshapes.shapes.UmlText import UmlText
from umlshapes.shapes.UmlUseCase import UmlUseCase


class TestIdentifierMixin(UnitTestBaseW):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 01 September 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()
        OGLInitialize()

    def tearDown(self):
        super().tearDown()

    def testUmlActorEquality(self):

        actor:     Actor    = Actor(actorName='John Wayne')
        umlActor:  UmlActor = UmlActor(actor=actor)

        umlActor2: UmlActor = umlActor

        self.assertTrue(umlActor == umlActor2, 'My __equ__ is not working')

    def testUmlActorInEquality(self):

        modelActor: Actor    = Actor(actorName='John Wayne')
        umlActor:   UmlActor = UmlActor(actor=modelActor)

        modelActor2: Actor    = Actor(actorName='John Wayne II')
        umlActor2:   UmlActor = UmlActor(actor=modelActor2)

        self.assertFalse(umlActor == umlActor2, 'My __equ__ is not working')

    def testUmlClassInEquality(self):

        modelClass: Class   = Class(name='BogusClass')
        umlClass:  UmlClass = UmlClass(modelClass=modelClass)

        modelClass2: Class  = Class(name='BogusClass2')
        umlClass2: UmlClass = UmlClass(modelClass=modelClass2)

        self.assertFalse(umlClass == umlClass2, 'Class equality not working')

    def testUmlNoteEquality(self):
        modelNote: Note    = Note(content='I am a note')
        umlNote:   UmlNote = UmlNote(note=modelNote)

        umlNote2: UmlNote = umlNote

        self.assertTrue(umlNote == umlNote2, 'Note equality not working')

    def testUmlTextEquality(self):

        umlText:  UmlText = UmlText()
        umlText2: UmlText = umlText
        self.assertEqual(umlText, umlText2, 'Text equality is not working')

    def testUseCaseInEquality(self):
        umlActor:  UmlActor = UmlActor()
        umlActor2: UmlActor = UmlActor()

        self.assertNotEqual(umlActor, umlActor2, 'Actor equal is wrong')

    def testUniqueIds(self):

        modelActor: Actor    = Actor(actorName='John Wilkes Booth')
        umlActor:   UmlActor = UmlActor(actor=modelActor)

        umlActor2:  UmlActor = UmlActor()

        self.assertFalse(umlActor.id == umlActor2.id, 'IDs should be unique')

    def testUmlActorInvalidGetId(self):
        """
        These tests make sure that the IdentifierMixin is place before any
        shape mixin.
        See Python left to right method resolution order (MRO)
        """
        umlActor: UmlActor = UmlActor()
        self.assertRaises(InvalidOperationError, lambda: umlActor.GetId())

    def testUmlUseCaseInvalidGetId(self):
        umlUseCase: UmlUseCase = UmlUseCase()
        self.assertRaises(InvalidOperationError, lambda: umlUseCase.GetId())

    def testUmlUmlNoteInvalidGetId(self):
        umlNote: UmlNote = UmlNote()

        try:
            umlNote.GetId()
            self.assertFalse(True, 'Where is our exception')
        except InvalidOperationError:
            self.assertTrue(True, 'We should get this exception')
        # self.assertRaises(InvalidOperationError, lambda: umlNote.GetId(), 'Incorrect MRO placement')

    def testUmlTextInvalidGetId(self):
        umlText: UmlText = UmlText()
        try:
            umlText.GetId()
            self.assertFalse(True, 'Where is our exception')
        except InvalidOperationError:
            self.assertTrue(True, 'We should get this exception')

        # self.assertRaises(InvalidOperationError, lambda: umlText.GetId(), 'Incorrect MRO placement')

    def testUmlClassInvalidGetId(self):
        umlClass: UmlClass = UmlClass()

        try:
            umlClass.GetId()
            self.assertFalse(True, 'Where is our exception')
        except InvalidOperationError:
            self.assertTrue(True, 'We should get this exception')
        # self.assertRaises(InvalidOperationError, lambda: umlClass.GetId(), 'Incorrect MRO placement')

    def testUmlLinkInvalidGetId(self):

        modelLink: Link   = Link()
        umlLink:  UmlLink = UmlLink(link=modelLink)
        try:
            umlLink.GetId()
            self.assertFalse(True, 'Where is our exception')
        except InvalidOperationError:
            self.assertTrue(True, 'We should get this exception')

        # self.assertRaises(InvalidOperationError, lambda: umlLink.GetId(), 'Incorrect MRO placement')

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestIdentifierMixin))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
