
from datetime import datetime
from typing import cast

from unittest import TestSuite
from unittest import main as unitTestMain

from codeallyadvanced.ui.UnitTestBaseW import UnitTestBaseW
from umlmodel.Class import Class
from umlmodel.Note import Note
from umlmodel.enumerations.LinkType import LinkType

from umlshapes.commands.CreateLinkCommand import CreateLinkCommand
from umlshapes.commands.CreateUmlClassCommand import CreateUmlClassCommand
from umlshapes.commands.CreateUmlNoteCommand import CreateUmlNoteCommand
from umlshapes.frames.ClassDiagramFrame import ClassDiagramFrame
from umlshapes.lib.ogl import OGLInitialize
from umlshapes.links.UmlNoteLink import UmlNoteLink

from umlshapes.pubsubengine.IUmlPubSubEngine import IUmlPubSubEngine
from umlshapes.pubsubengine.UmlPubSubEngine import UmlPubSubEngine
from umlshapes.shapes.UmlClass import UmlClass
from umlshapes.shapes.UmlNote import UmlNote

from umlshapes.types.UmlPosition import UmlPosition


class TestCreateUmlLinkCommand(UnitTestBaseW):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 17 August 2026
    """

    @property
    def timeStamp(self) -> int:

        dt = datetime.now()

        return dt.microsecond

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()
        OGLInitialize()
        self._umlPubSubEngine: IUmlPubSubEngine = UmlPubSubEngine()
        self._classDiagramFrame: ClassDiagramFrame = ClassDiagramFrame(parent=self._listeningWindow, umlPubSubEngine=self._umlPubSubEngine)

    def tearDown(self):
        super().tearDown()

    def testNoteLink(self):
        """
        Regression test caught by the UML Diagrammer UI tests

        """

        createUmlClassCommand: CreateUmlClassCommand = CreateUmlClassCommand(
            umlFrame=self._classDiagramFrame,
            umlPosition= UmlPosition(x=100, y=100),
            umlPubSubEngine = self._umlPubSubEngine,
            modelClass = None
        )
        createUmlNoteCommand: CreateUmlNoteCommand = CreateUmlNoteCommand(
            umlFrame=self._classDiagramFrame,
            umlPosition=UmlPosition(x=200, y=200),
            umlPubSubEngine=self._umlPubSubEngine
        )
        umlClass: UmlClass = createUmlClassCommand._createPrototypeInstance()
        umlNote:  UmlNote  = createUmlNoteCommand._createPrototypeInstance()

        umlClass.umlFrame = self._classDiagramFrame
        umlNote.umlFrame  = self._classDiagramFrame

        createUmlLinkCommand: CreateLinkCommand = CreateLinkCommand(
            umlFrame=self._classDiagramFrame,
            partialName=f'UnitTestNoteLink-{self.timeStamp}',
            linkType=LinkType.NOTELINK,
            sourceShape=umlNote,
            destinationShape=umlClass,
            umlPubSubEngine=self._umlPubSubEngine
        )
        createUmlLinkCommand._createLink()
        umlNoteLink: UmlNoteLink = cast(UmlNoteLink, createUmlLinkCommand.umlLink)

        modelNote:  Note  = cast(UmlNote, umlNoteLink.sourceShape).modelNote
        modelClass: Class = cast(UmlClass, umlNoteLink.destinationShape).modelClass

        self.assertIsNotNone(modelNote)
        self.assertIsNotNone(modelClass)

    def testInterfaceLink(self):

        pass


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestCreateUmlLinkCommand))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
