
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from umlshapes.CoordinateUtils import CoordinateUtils
from umlshapes.mixins.TopLeftMixin import Rectangle

from umlshapes.types.UmlLine import UmlLine
from umlshapes.types.UmlPosition import UmlPoint

BOUNDING_RECTANGLE: Rectangle = Rectangle(
    left=100,
    top=100,
    right=500,
    bottom=500
)


class TestCoordinateUtils(UnitTestBase):
    """
    Tests for CoordinateUtils;  File generated by Gemini, by moving my code;  I feel so dirty
    """

    def setUp(self):
        super().setUp()

    def testIsLineWhollyContainedByRectangleTrue(self):

        rectangle: Rectangle = Rectangle(left=100, top=100, right=400, bottom=400)
        umlLine:   UmlLine   = UmlLine(start=UmlPoint(x=200, y=200), end=UmlPoint(x=300, y=300))

        answer: bool = CoordinateUtils.isLineWhollyContainedByRectangle(umlLine=umlLine, boundingRectangle=rectangle)
        self.assertTrue(answer, 'The line is inside the rectangle')

    def testIsLineWhollyContainedByRectangleFalseEndPointBelow(self):

        rectangle: Rectangle = Rectangle(left=100, top=100, right=400, bottom=400)
        umlLine:   UmlLine   = UmlLine(start=UmlPoint(x=200, y=200), end=UmlPoint(x=500, y=500))

        answer: bool = CoordinateUtils.isLineWhollyContainedByRectangle(umlLine=umlLine, boundingRectangle=rectangle)
        self.assertFalse(answer, 'The line end is outside the rectangle')

    def testIsLineWhollyContainedByRectangleFalseStartPointAbove(self):

        rectangle: Rectangle = Rectangle(left=100, top=100, right=50, bottom=50)
        umlLine:   UmlLine   = UmlLine(start=UmlPoint(x=200, y=200), end=UmlPoint(x=300, y=300))

        answer: bool = CoordinateUtils.isLineWhollyContainedByRectangle(umlLine=umlLine, boundingRectangle=rectangle)
        self.assertFalse(answer, 'The line start is outside the rectangle')

    def testIsPointInsideRectangleTrue(self):
        """
        Just inside the rectangle
        """

        umlPoint: UmlPoint = UmlPoint(x=BOUNDING_RECTANGLE.left + 5, y=BOUNDING_RECTANGLE.top + 9)

        ans: bool = CoordinateUtils.isPointInsideRectangle(point=umlPoint, rectangle=BOUNDING_RECTANGLE)
        self.assertTrue(ans, 'oops the point should be in the rectangle')

    def testIsPointInsideRectangleFalse(self):
        """
        Just outside the rectangle
        """

        umlPoint: UmlPoint = UmlPoint(x=BOUNDING_RECTANGLE.right + 5, y=BOUNDING_RECTANGLE.bottom + 9)

        ans: bool = CoordinateUtils.isPointInsideRectangle(point=umlPoint, rectangle=BOUNDING_RECTANGLE)
        self.assertFalse(ans, 'oops the point should be outside the rectangle')

    def testIsShapeInRectangleTrue(self):
        boundingRectangle: Rectangle = Rectangle(
            left=100,
            top=100,
            right=500,
            bottom=500
        )
        testShape: Rectangle = Rectangle(
            left=120,
            top=120,
            right=200,
            bottom=200
        )
        ans: bool = CoordinateUtils.isShapeInRectangle(boundingRectangle=boundingRectangle, shapeRectangle=testShape)
        self.assertTrue(ans, 'Hey!!  This shape is wholly contained')

    def testIsPartialShapeInRectangleFalse(self):
        boundingRectangle: Rectangle = Rectangle(
            left=100,
            top=100,
            right=500,
            bottom=500
        )
        testShape: Rectangle = Rectangle(
            left=300,
            top=300,
            right=400,
            bottom=700
        )
        ans: bool = CoordinateUtils.isShapeInRectangle(boundingRectangle=boundingRectangle, shapeRectangle=testShape)
        self.assertFalse(ans, 'Hey!!  This shape is not wholly contained')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestCoordinateUtils))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
